enabled=true
debug=false
target.host=127.0.0.1
target.port=6567
target.name=MDT Target Server
dispatch.chat=true
dispatch.info=true
dispatch.kick=true
dispatch.kickDuration=0
dispatch.uriTemplate=mdt://redirect?host=%s&port=%d&name=%s
dispatch.chatTemplate=[accent][MDT Redirect][] %s
dispatch.infoTemplate=[accent]Server redirect prepared[]\n%s
dispatch.kickTemplate=MDT_REDIRECT %s
